server.port=8080

gemini.api.key=AIzaSyAqVKsiOdnDx2gKKNCYkGoIrEgFEh97dgY

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.com.smarthire=DEBUG